
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: wsdd-springcloud-zuul

server:
  port: 1993

zuul:
  routes:
    api-a:
      path: /dung/**
      serviceId: wsdd-springcloud-web
